Adding Andes Tag Choice
mercadolibre/fury_andesui-ios pull request #123
Opened 2020-09-28 16:30 UTC by fconilmeli

### Thanks for contributing to Andes UI!
## Description
Describe why we need these changes in the lib.
Try to answer these questions:
- What is it about?
- How does it work?
## Affected component
Is highly probable that this new code affects directly one (or more?) components inside this lib. Tell us who they are!
## RFC Link
If this change was discussed on RFC please paste link here.
## Screenshots / GIFs
This is a UI library, delight us with some stunning images.
## Checks
Are you sure you followed all those steps? If so, repeat after me "I solemnly swear that ...":
   - [ ] I have coded an example inside the Demo App,
   - [ ] I have added proper tests,
   - [ ] I have modified the Changelog.md file,
   - [ ] I have updated GitHub wiki,
   - [ ] I have the explicit approval of one or more members of the UX Team,
   - [ ] I have checked that this code is ObjC compliant.
   - [ ] I have checked that all the new public enums conform to AndesEnumStringConvertible.
## Change type
This is easy, let us know what this code is about:
   - [ ] This code adds a new component
   - [ ] This code includes improvements to an existent component
   - [ ] This code improves or modifies ONLY the Demo App.

2020-09-28 16:30 UTC, furyGorgoryAdmin commented
### Informative Menu <h2>  ### 

### Use any of these tags in a pull request description or leave a comment ### 
| Tag | Description |
|---|---|
| **[canary]**| Creates a build that can only be deployed with canary strategy. | 
| **[build]** |  Creates version or build from a branch that has been tagged as "no releasable". | 
| **[name:version-name]** |Specify the name of the build. For example: [build] [name:1.2.3-name] or [canary] [name:1.2.3-name].|
| **[major]** | To automatically increase the first position of the version. For example: [build] [major] or [canary] [major].|
| **[minor]** | To automatically increase the second position of the version. For example: [build] [minor] or [canary] [minor]. |
| **[patch]** | To automatically increase the third position of the version. For example: [build] [patch] or [canary] [patch].|  

[For more information about ci-cd](http://docs.furycloud.io/?lang=esp&section=businessassurance)
[For more information about semver](https://semver.org/#summary)

2020-09-28 16:38 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/AndesTagChoice.swift
> +    @objc public var state: AndesTagState = .idle {
falta agregarle un comentario de documentacion

2020-09-28 16:38 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/AndesTagChoice.swift
> +    @objc public var type: AndesTagChoiceType = .simple {
tambien falta comentario

2020-09-28 16:40 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/Config/AndesTagViewConfig.swift
> -    var isDismissable: Bool = false
choice y simple tienen la misma configuracion, no conoce de estados ni si es dismiseable, solo conoce componentes de UI

2020-09-28 16:40 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/State/AndesTagStateIdle.swift
> +    var textColor: UIColor = UIColor(red: 0.00, green: 0.00, blue: 0.00, alpha: 0.80)
hay que agregar los colores a la clase de Andes

2020-09-28 16:42 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/Type/AndesTagChoiceTypeDropDown.swift
> +    var rightButtonImageName: String? = "andes_ui_chevron_down_16"
esto es algo que me hace un poco de ruido, los State manejan colores y el contenido de la derecha, el Type (dropdown-simple) por el momento solo tienen diferentes el contenido de la derecha y medio como que estoy duplicando State maneja contenido de la derecha pero el Type tambien

2020-09-29 15:05 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/View/AndesTagView.swift
> +class AndesTagView: AndesTagAbstractView {
No se si aca me conviene crear dejar esta `AndesTagView` como estaba => `AndesTagSimpleView` y crear otra vista igual para el choice `AndesTagChoiceView` y tener las dos separadas

2020-09-30 19:32 UTC, nrostanml commented on LibraryComponents/Classes/Core/AndesTag/SideContent/Views/AndesTagLeftContentIconView.swift
> +        imageView.image = imageView.image?.withRenderingMode(.alwaysTemplate)
🤔  no me deja 100% convencido que aceptemos un UIImage cualquiera como icono pero que forcemos a que sea siempre renderizado como template...  @samuelsainz vos que opinás?

2020-09-30 19:44 UTC, samuelsainz commented on LibraryComponents/Classes/Core/AndesTag/SideContent/Views/AndesTagLeftContentIconView.swift
> +        imageView.image = imageView.image?.withRenderingMode(.alwaysTemplate)
@nrostanml Siendo que este caso es solo para iconos no lo veo mal, la idea de andes con los iconos es esta no? Son una especie de template que se pueden cambiar de colores. 

Como para imágenes tenemos la clase `AndesTagLeftContentImageView`, no habría problema en que los iconos sean "templates". 

Si no entendí mal, la necesidad particular que tienen es que necesitan que en el estado Selected el icono tome el mismo color que el Tag. Supongo que no todos los iconos que se podrían usar acá aplicarían a ser parte de Andes, con esto te aseguras que el icono se ponga como template.

2020-09-30 22:44 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/SideContent/Views/AndesTagLeftContentIconView.swift
> +        imageView.image = imageView.image?.withRenderingMode(.alwaysTemplate)
exacto, para el caso de los Choice el icono toma el color del estado

2020-09-30 22:46 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/AndesTagSimple.swift
> +    }
porque los TagSimple no hacen nada cuando tapeas la vista, al menos por el momento no, queda abierto para un futuro si se quiere hacer algo al tapear la vista

2020-10-06 19:03 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/View/AndesTagChoiceView.swift
> +        self.rightButton.isUserInteractionEnabled = false
esto es porque a la hora de agregarlo en una collection view, el botón toma todos los eventos, y tampoco es necesario para este tag que ese boton sea funcional

2020-10-07 20:49 UTC, samuelsainz requested changes

2020-10-07 20:49 UTC, samuelsainz commented on LibraryComponents/Classes/Core/AndesTag/View/AndesTagSimpleView.swift
> -            self.rightButton.accessibilityLabel = "Cerrar".localized()
Estamos perdiendo accesibilidad acá, este texto habría que incluírlo a la config y setear uno u otro según cuál es el botón.

2020-10-07 20:59 UTC, fconilmeli commented on LibraryComponents/Classes/Core/AndesTag/View/AndesTagSimpleView.swift
> -            self.rightButton.accessibilityLabel = "Cerrar".localized()
uhh si se me pasó, no deberia ser un cambio esto, gracias por el catch

2020-10-08 19:41 UTC, nrostanml approved these changes

2020-10-08 19:42 UTC, samuelsainz approved these changes

2020-10-08 19:42 UTC, merged