Fix / AndesThumbnailSize
mercadolibre/fury_andesui-ios pull request #132
Opened 2020-10-15 19:22 UTC by mzangl-meli

### Thanks for contributing to Andes UI!
## Description
Align to Android AndesThumbnailSize key names

## Affected component
AndesThumbnail

## Checks
Are you sure you followed all those steps? If so, repeat after me "I solemnly swear that ...":
   - [X] I have modified the Changelog.md file,
   - [X] I have checked that all the new public enums conform to AndesEnumStringConvertible.
## Change type
This is easy, let us know what this code is about:
   - [X] This code includes improvements to an existent component

2020-10-16 13:10 UTC, nrostanml approved these changes

2020-10-16 13:11 UTC, nrostanml requested changes
El changelog quedó mal, la 3.10 ya salió, podes crear la 3.11?

2020-10-19 14:57 UTC, nrostanml commented
@mzangl-meli esto es un breaking change, sabemos si tiene un impacto grande? si hay equipos que usen thumbnail cambiando el size por interface builder van a ver el error en runtime no en compile...

2020-10-19 15:22 UTC, mzangl-meli commented
> @mzangl-meli esto es un breaking change, sabemos si tiene un impacto grande? si hay equipos que usen thumbnail cambiando el size por interface builder van a ver el error en runtime no en compile...

@nrostanml dejame revisar nuevamente del lado de credit card, el tema saltó que tambien es un breacking change del lado de android, y con @jperezgonzal llegamos a querer alinear iOS. El impacto es porq ya desde el middle estámos recibiendo `paymentsData` y no el valor `XX` directamente.

2020-10-19 18:30 UTC, mzangl-meli commented
@nrostanml del lado de Credit Card, los modulos de Payment, Disable ya tenemos actualizado el middle para enviar la configuración con `size_XX`
faltaría revisar el middle del módulo Upgrade, y serían todos los que están usando AndesThumbnail

2020-10-19 18:43 UTC, nrostanml approved these changes

2020-10-19 18:49 UTC, nrostanml approved these changes

2020-10-19 18:55 UTC, merged