AndesList
mercadolibre/fury_andesui-ios pull request #143
Opened 2020-11-03 16:00 UTC by joalonsopint

### Thanks for contributing to Andes UI!
## Description
Creación de AndesList para la implementación de listas, las filas deben ser del mismo tipo que la lista como restricción del componente.

Contiene dos APIs públicas:

**AndesList:** Permite definir la lista a utilizar, se deben tener las siguientes consideraciones

- Recibe un parámetro que le define el tipo de lista a utilizar (simple, chevron)

- Se deben implementar los delegados y los dataSources (AndesListDelegate y AndesListDataSource)

- Se debe definir el número de filas a pintar

- Permite habilitar o no la linea que separa cada fila, por defecto no está habilitada

- Permite recargar la lista

**AndesListCell:** Permite implementar una celda en la lista, estas pueden ser de los siguientes tipos

- **AndesSimpleCell:** Celda simple con las siguientes propiedades

     - title: Implementa el título de la celda (Obligatorio)

     - subTitle: Implementa el sub título de la celda (Opcional)

     - size: Definir el tamaño de la celda (small, medium, large) por defecto es medium

     - thumbnail: Recibe un objeto de tipo AndesThumbnail, el cual puede ser icono o imagen.

- **AndesChevronCell:** Celda con chevron con las siguientes propiedades

     - title: Implementa el título de la celda (Obligatorio)

     - subTitle: Implementa el sub título de la celda (Opcional)

     - size: Definir el tamaño de la celda (small, medium, large) por defecto es medium

     - thumbnail: Recibe un objeto de tipo AndesThumbnail, el cual puede ser icono o imagen.

## Affected component
N/A
## RFC Link
https://docs.google.com/document/d/1lsJ_Oz-XplkwAMbINjTSdz8imvVDUqIbElZZNKsUo5Q
## Screenshots / GIFs
<img width="584" alt="image" src="https://user-images.githubusercontent.com/69221534/98008941-097dce00-1dc3-11eb-9b96-ee80cdfec7f0.png">
<img width="584" alt="image" src="https://user-images.githubusercontent.com/69221534/98008957-0da9eb80-1dc3-11eb-9ada-1fbec52aa859.png">

## Checks
Are you sure you followed all those steps? If so, repeat after me "I solemnly swear that ...":
   - [x] I have coded an example inside the Demo App,
   - [x] I have added proper tests,
   - [ ] I have modified the Changelog.md file,
   - [ ] I have updated GitHub wiki,
   - [ ] I have the explicit approval of one or more members of the UX Team,
   - [x] I have checked that this code is ObjC compliant.
   - [x] I have checked that all the new public enums conform to AndesEnumStringConvertible.
## Change type
This is easy, let us know what this code is about:
   - [x] This code adds a new component
   - [ ] This code includes improvements to an existent component
   - [ ] This code improves or modifies ONLY the Demo App.

2020-11-03 16:52 UTC, haurbano commented on LibraryComponents/Classes/Core/AndesList/AndesChevronCell.swift
> +        guard let size = size, let subTitle = subTitle else { return }
Jona, por que tenemos AndesListSize y subTitle como opcional si al ser nil cualquiera de los dos no vamos a hacer nada (vamos a hacer return)? No deberian en ese caso ser obligatorios?

2020-11-03 17:25 UTC, haurbano commented on LibraryComponents/Classes/Core/AndesList/AndesChevronCell.swift
> +                                                          subTitle: !subTitle.isEmpty,
El nombre `subTitle` lo tienes el el metodo `cellConfig` como un String pero en el metodo `provide` es un boolean. Se podria renombrar para que sea más intuitivo? Por ejemplo: `subTitleNoEmpty`, pensate un mejor nombre igual XD.

2020-11-03 17:25 UTC, haurbano commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +    @IBOutlet weak var paddingBottomThumbnailConstraint: NSLayoutConstraint!
Deberiamos tener privado estos campos? Puede ser?

2020-11-03 17:50 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesChevronCell.swift
> +        guard let size = size, let subTitle = subTitle else { return }
Hami, para el dev es opcional, pero internamente si el size viene nulo, su valor por defecto es medium y lo mismo pasa con el sub titulo, si el dev no lo implementa su valor por defecto es un string vacío, ese return es para asegurarnos que esos valores no sean utilicen como nulos y genere un crash.

2020-11-03 18:12 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +    @IBOutlet weak var paddingBottomThumbnailConstraint: NSLayoutConstraint!
Hami, estos no se pueden acceder por que son internos, pero si ajusté otros parámetros como internos ;) gracias!

2020-11-04 23:18 UTC, RodriP commented on LibraryComponents/Classes/Core/AndesTag/View/AndesTagAbstractView.swift
> +        func setup() {
esto lo dejaria como estaba antes sin las tabs

2020-11-05 04:14 UTC, samuelsainz commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +        if let imageSize = customCell.thumbnailSize {
Creo que acá deberías contemplar el caso en el que imageSize es nil y setear las constraints en 0, porque la celda puede ser reutilizada. Si reutilizas una que tenía imagen para mostrar una que no, te van a quedar las constraints para la configuración con imagen

2020-11-05 04:14 UTC, samuelsainz commented on LibraryComponents/Classes/Core/AndesList/Types/AndesCellType.swift
> +        case .radioButton: return "RADIOBUTTOM"
typo con la M en "RADIOBUTTOM"

2020-11-05 04:14 UTC, samuelsainz commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +@objc public class AndesListCell: UITableViewCell {
Agregaría un poco más de 🍎 doc a estas clases que son publicas

2020-11-05 04:14 UTC, samuelsainz commented
Muy bueno Jona 👏

2020-11-05 12:14 UTC, joalonsopint commented on Example/AndesUI - UITests/UITestCard.swift
> +
Creo que esos espacios se ajustaron automáticamente por que ejecuté el comando swiftlint autocorrect

2020-11-05 12:16 UTC, joalonsopint commented on Example/AndesUI/Home/Views/HomeViewController.swift
> +        presenter.presentThumbnail()
Por ahora solo tenemos acción para la celda

2020-11-05 12:18 UTC, joalonsopint commented on Example/AndesUI/List/Router/ListRouter.swift
> +        view = AndesShowcasePageViewController(controllers: [ListViewController(),
Aquí si está bien Rodri, es algo común en iOS y en si el proyecto tiene las clases de los ejemplos con ese complemento en el nombre

2020-11-05 12:21 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesChevronCell.swift
> +                            subTitle: String,
No Rodri, es opcional, esta clase tiene dos init, uno para Objc y otro para Swift, esto por que para Objc no permite variables opcionales, en el init de Swift está el opcional y es el que le da valores a este método cellConfig en caso que el valor sea nulo

2020-11-05 12:23 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesChevronCell.swift
> +        self.paddingLeftCell = config.paddingLeft
Esta clase configura la celda a pintar, se te ocurre alguna idea para no tenerlo aquí?

2020-11-05 12:47 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +    @objc public var numberOfRows: Int = 0
Woooo Samu!, lo cambio al dataSource

2020-11-05 12:48 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +    var numberOfSection: Int = 1
Si, para esta primera entrega solo vamos a soportar una sección, pero si debemos soportar varias secciones en el futuro

2020-11-05 12:49 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +    @objc public var separatorStyle: AndesSeparatorStyle = .none
Si Rodri, una lista puede o no tener un separador, estos valores los nombré igual que lo hace de forma nativa.

2020-11-05 12:53 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +                           forCellReuseIdentifier: "AndesListCevronViewCell")
No entendí estos dos comentarios Samu

2020-11-05 12:53 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +@objc public class AndesListCell: UITableViewCell {
Sip, aún no he terminado esta parte de doc ;)

2020-11-05 12:55 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +
Si, de acuerdo ;)

2020-11-05 13:09 UTC, samuelsainz commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +                           forCellReuseIdentifier: "AndesListCevronViewCell")
Jona, perdon si no me explique bien, en el nombre del nib hay un typo con la palabra Chevron, en vez de Chevron dice Cevron 😅

2020-11-05 13:25 UTC, RodriP commented on Example/AndesUI/Home/Views/HomeViewController.swift
> +        presenter.presentThumbnail()
Ah bien, y este metodo para que lo usaríamos ?

2020-11-05 13:26 UTC, RodriP commented on Example/AndesUI/List/Router/ListRouter.swift
> +        view = AndesShowcasePageViewController(controllers: [ListViewController(),
Perfecto 👍

2020-11-05 13:43 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +                           forCellReuseIdentifier: "AndesListCevronViewCell")
Huy si, no lo vi, creo que me toca cambiar de gafas 👀

2020-11-05 13:53 UTC, joalonsopint commented on Example/AndesUI/Home/Views/HomeViewController.swift
> +        presenter.presentThumbnail()
Este método es para mostrar la vista de Thumbnail, supongo que muestra el cambio por swiftlint

2020-11-05 14:13 UTC, joalonsopint commented
> Muy bueno Jona 👏

Te animas con otros dos ?😁🤞🏼
https://github.com/mercadolibre/fury_andesui-ios/pull/150
https://github.com/mercadolibre/fury_andesui-ios/pull/151

2020-11-05 19:39 UTC, nrostanml commented on Example/AndesUI/List/View/ListObjcViewController.m
> +*/
podemos borrar esto?

2020-11-05 19:41 UTC, joalonsopint commented on Example/AndesUI/List/View/ListObjcViewController.m
> +*/
El otro PR ya tiene mejor ajustado la parte de la testapp 😁 por si quieres hecharle un ojo 👀

2020-11-05 19:50 UTC, nrostanml approved these changes

2020-11-05 19:50 UTC, nrostanml commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +    @IBOutlet weak var paddingBottomThumbnailConstraint: NSLayoutConstraint!
Esto no debería ser más abstracto? porque tiene referencias a thumbnail o coosas que no todas las celdas pueden llegar a tener?

2020-11-05 19:50 UTC, nrostanml commented on LibraryComponents/Classes/Core/AndesList/Types/AndesListCellLargeType.swift
> +    var separatorThumbnailWidth: CGFloat? = 0
idem acá, no deberían ser dos structs distintos? osea el size y el type no son diferentes?

2020-11-05 19:50 UTC, nrostanml commented on LibraryComponents/Classes/Core/AndesTextField/View/Default/AndesTextFieldDefaultView.swift
> +extension AndesTextFieldAbstractView: UITextFieldDelegate {
esto no rompe el textfield?

2020-11-05 19:51 UTC, nrostanml requested changes
No podemos separar más las confiigs de size y type de las celdas?

2020-11-05 19:55 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesTextField/View/Default/AndesTextFieldDefaultView.swift
> +extension AndesTextFieldAbstractView: UITextFieldDelegate {
Si, tienes razón, lo ajusto, creo que me estaba mostrando error por eso lo cambié

2020-11-06 12:50 UTC, tinchovictory commented on LibraryComponents/Classes/Core/AndesTextField/View/Default/AndesTextFieldDefaultView.swift
> +extension AndesTextFieldAbstractView: UITextFieldDelegate {
Esto se cambio para que funcione el AndesTextFieldCode

2020-11-06 14:20 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +@objc public class AndesListCell: UITableViewCell {
<img width="559" alt="image" src="https://user-images.githubusercontent.com/69221534/98376286-3de6c980-2011-11eb-9dde-cf06f8da7a06.png">

2020-11-10 18:11 UTC, nrostanml requested changes

2020-11-10 18:11 UTC, nrostanml commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +    public init(type: String) {
acá lo mismo, no debería venir el enum? y podemos ponerle .simple como default..?

2020-11-10 18:11 UTC, nrostanml commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +                           forCellReuseIdentifier: "AndesListChevronViewCell")
podemos sacarlo a otra función así cuando agreguemos más celdas no se vuelve un choclo el setup?

2020-11-10 18:11 UTC, nrostanml commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +    }
hay métodos en este protcolo que no usan nada de la lista en si, no podemos pasarle el dataSource al internalDataSource y el delegate al internalDelegate y en este dejar solo los métodos que leen alguna property de la lista? te parece más confuso..? el miedo que tengo acá es que a medida que agreguemos métodos del delegate y datasource nativo esto va a ir creciendo innecesariamente... (me refiero a en los constructores de internalDataSource pasarle además de este protocolo el AndesListDataSource por ejemplo..)

2020-11-10 18:11 UTC, nrostanml commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +    var type: AndesCellType?
podemos hacer esto public(get) ? así le damos una herramienta al dev para chequear en el didSelect?

2020-11-10 20:24 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesList/AndesListCell.swift
> +    var type: AndesCellType?
Esta variable no es pública, es asignada internamente

2020-11-11 17:20 UTC, nrostanml submitted a review, later dismissed

2020-11-11 17:44 UTC, nrostanml approved these changes

2020-11-11 17:47 UTC, merged