Feature/date picker
mercadolibre/fury_andesui-ios pull request #163
Opened 2020-11-17 18:19 UTC by AndriuCoelho

### Thanks for contributing to Andes UI!
## Description
- Date Picker or Calendar is a date choice component. It is possible to limit a range of dates (useful for my bill payment team) or it is possible to initialize a common calendar.
Try to answer these questions:
- What is it about?
- Component of date choice
- How does it work?
It is possible to choose a date in a range or any date (depending on the initialization)
## Affected component
Is highly probable that this new code affects directly one (or more?) components inside this lib. Tell us who they are!
## RFC Link
- https://docs.google.com/document/d/1g31GzB9CqsGNrkGj6iDtjHBVVgGbfuNczIzTvah1dgQ/edit#heading=h.ixm8d2k39d9a
## Screenshots / GIFs

1) Calendar with range validation (useful for bill payment):

![datepicker-gif2](https://user-images.githubusercontent.com/7536739/99429537-eab12880-28e6-11eb-8fa1-57933a7ca18a.gif)

2) Normal calendar:

![datepicker-gif1](https://user-images.githubusercontent.com/7536739/99429601-fdc3f880-28e6-11eb-889c-9b607e3e7c2a.gif)

## Checks
Are you sure you followed all those steps? If so, repeat after me "I solemnly swear that ...":
   - [ ] I have coded an example inside the Demo App,
   - [ ] I have added proper tests,
   - [ ] I have modified the Changelog.md file,
   - [ ] I have updated GitHub wiki,
   - [ ] I have the explicit approval of one or more members of the UX Team,
   - [ ] I have checked that this code is ObjC compliant.
   - [ ] I have checked that all the new public enums conform to AndesEnumStringConvertible.
## Change type
This is easy, let us know what this code is about:
   - [x] This code adds a new component
   - [ ] This code includes improvements to an existent component
   - [ ] This code improves or modifies ONLY the Demo App.

2020-11-18 12:17 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesDatePicker/Config/AndesDatePickerSettingCollection.swift
> +    init(baseDate: Date, daysToRender days: [AndesDayDatePicker]) {
Pienso que la variable days: [AndesDayDatePicker] no da claridad a que se está refiriendo, crees que podamos buscar un nombre que este un poco más asociado al objeto?

2020-11-18 12:21 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesDatePicker/Model/AndesDayDatePicker.swift
> +        return days
Mismo comentario anterior, variable days

2020-11-18 12:23 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesDatePicker/AndesDatePicker.swift
> +    @objc public func setDatePickerDate(maxDate: Date? = nil, callback: @escaping ((Date?, Bool) -> Void)) {
Te parece si añadimos documentación con las recomendaciones de Apple?, definiendo cada variable, así es fácil consultarla desde el mismo Xcode cuando se integra

2020-11-18 12:25 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesDatePicker/Config/AndesDatePickerSettingCollection.swift
> +@objc public class AndesDatePickerSettingCollection: NSObject, UICollectionViewDataSource {
Está bien que esta clase sea pública?

2020-11-18 12:28 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesDatePicker/Model/AndesDayDatePicker.swift
> +@objc public class AndesDayDatePicker: NSObject {
Está bien que esta clase sea pública?

2020-11-18 12:30 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesDatePicker/View/AndesDatePickerAbstractView.swift
> +        buttonPrimary.text = "Confirmar"
Esto podría estar localizado?

2020-11-18 12:45 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesDatePicker/View/AndesDatePickerHeaderView.swift
> +    let previousButton: UIButton = {
Este podría ser privado como los demás?

2020-11-18 12:47 UTC, joalonsopint requested changes
Te dejé algunos comentarios

2020-11-19 12:47 UTC, AndriuCoelho commented on LibraryComponents/Classes/Core/AndesDatePicker/View/AndesDatePickerHeaderView.swift
> +    let previousButton: UIButton = {
si

2020-11-19 12:52 UTC, AndriuCoelho commented on LibraryComponents/Classes/Core/AndesDatePicker/Config/AndesDatePickerSettingCollection.swift
> +    init(baseDate: Date, daysToRender days: [AndesDayDatePicker]) {
ok

2020-11-19 12:53 UTC, AndriuCoelho commented on LibraryComponents/Classes/Core/AndesDatePicker/Model/AndesDayDatePicker.swift
> +        return days
ok

2020-11-19 12:53 UTC, AndriuCoelho commented on LibraryComponents/Classes/Core/AndesDatePicker/AndesDatePicker.swift
> +    @objc public func setDatePickerDate(maxDate: Date? = nil, callback: @escaping ((Date?, Bool) -> Void)) {
no entendí.. cual es la sugerencia?

2020-11-19 13:00 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesDatePicker/AndesDatePicker.swift
> +    @objc public func setDatePickerDate(maxDate: Date? = nil, callback: @escaping ((Date?, Bool) -> Void)) {
Añadir documentación, puedes hacerlo con el mismo Xcode automáticamente, te paso un link, https://nshipster.com/swift-documentation/
Si tienes dudas nos juntamos y lo vemos

2020-11-19 16:25 UTC, AndriuCoelho commented on LibraryComponents/Classes/Core/AndesDatePicker/AndesDatePicker.swift
> +    @objc public func setDatePickerDate(maxDate: Date? = nil, callback: @escaping ((Date?, Bool) -> Void)) {
ok

2020-11-19 19:29 UTC, joalonsopint commented on LibraryComponents/Classes/Core/AndesTextField/View/TextArea/AndesTextAreaView.swift
> +        textView.onNeedsBorderUpdate = { [weak self] (_: UIView) in
Esto cambió algo?

2020-11-19 19:31 UTC, joalonsopint commented on CHANGELOG.md
> +# v3.15.0
Creo que este debe ir en Unpublished

2020-11-23 13:48 UTC, joalonsopint approved these changes

2020-11-23 13:50 UTC, merged