Add tabbar badge extension
mercadolibre/fury_andesui-ios pull request #207
Opened 2021-01-25 15:04 UTC by Julima15

### Thanks for contributing to Andes UI!
## Description
Describe why we need these changes in the lib.
Try to answer these questions:
- What is it about?
- How does it work?
## Affected component
Is highly probable that this new code affects directly one (or more?) components inside this lib. Tell us who they are!
## RFC Link
If this change was discussed on RFC please paste link here.
## Screenshots / GIFs
This is a UI library, delight us with some stunning images.
## Checks
Are you sure you followed all those steps? If so, repeat after me "I solemnly swear that ...":
   - [ ] I have coded an example inside the Demo App,
   - [ ] I have added proper tests,
   - [ ] I have modified the Changelog.md file,
   - [ ] I have updated GitHub wiki,
   - [ ] I have the explicit approval of one or more members of the UX Team,
   - [ ] I have checked that this code is ObjC compliant.
   - [ ] I have checked that all the new public enums conform to AndesEnumStringConvertible.
## Change type
This is easy, let us know what this code is about:
   - [ ] This code adds a new component
   - [ ] This code includes improvements to an existent component
   - [ ] This code improves or modifies ONLY the Demo App.

2021-01-25 15:08 UTC, Julima15 commented on LibraryComponents/Classes/Core/AndesBadge/Extensions/UITabBarItem+AndesBadgeExtension.swift
> +        let pillView = AndesBadgePill(hierarchy: .loud, type: .error, border: .standard, size: .small, text: value)
no deberia poder modificarse la configuración del badge

2021-01-25 15:10 UTC, Julima15 commented on LibraryComponents/Classes/Core/AndesBadge/Extensions/UITabBarItem+AndesBadgeExtension.swift
> +    func setAndesBadge(with value: String?) {
para mostrar el badge tienen que ser numeros enteros mayores a cero.

Por ejemplo:
0
1
2
20

Si es mayor a 99 se fixea asi: 99+

2021-01-25 17:54 UTC, jbrunoAtMeli requested changes
sacar el Podfile.lock

2021-01-25 19:11 UTC, Julima15 commented
@jbrunoAtMeli listo!

2021-01-29 13:24 UTC, jbrunoAtMeli requested changes
No hay un ejemplo en el código de la testapp pero si el screenshot que muestra la tabbar con el badge.
Agregar test unitarios. 
Actualizar el changelog.  

gracias

2021-01-29 13:24 UTC, jbrunoAtMeli commented on LibraryComponents/Classes/Core/AndesBadge/Extensions/AndesTabBarValueBuilder.swift
> +    class func build(in item: UITabBarItem, for value: String?) -> String? {
debería ser
    value: Int
    y el builder lo transforma a String

2021-02-03 20:34 UTC, jbrunoAtMeli commented on LibraryComponents/Classes/Core/AndesBadge/Extensions/AndesTabBarValueBuilder.swift
> +    class func build(in item: UITabBarItem, for value: UInt) -> String? {
NOTE

Use UInt only when you specifically need an unsigned integer type with the same size as the platform’s native word size. If this isn’t the case, Int is preferred, even when the values to be stored are known to be nonnegative. A consistent use of Int for integer values aids code interoperability, avoids the need to convert between different number types, and matches integer type inference, as described in Type Safety and Type Inference.   FROM https://docs.swift.org/swift-book/LanguageGuide/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-XID_411

2021-02-03 20:38 UTC, Julima15 commented on LibraryComponents/Classes/Core/AndesBadge/Extensions/AndesTabBarValueBuilder.swift
> +    class func build(in item: UITabBarItem, for value: UInt) -> String? {
dale ahi lo cambio !

2021-02-03 20:43 UTC, Julima15 commented on LibraryComponents/Classes/Core/AndesBadge/Extensions/AndesTabBarValueBuilder.swift
> +    class func build(in item: UITabBarItem, for value: UInt) -> String? {
me falta agregar un ejemplo en el codigo

2021-02-04 21:13 UTC, Julima15 commented
@jbrunoAtMeli Despues de hacer la app de ejemplo y probar de forma manual(cambiar mas de una vez el badge) me di cuenta que habia cosas mal en la logica del dibujado del badge, corregi esa logica y modifique los test.

Estoy validando con UX la posición del badge sobre la imagen

2021-02-04 21:17 UTC, jbrunoAtMeli commented
@Julima15 perfecto avísame cuando lo pueda revisar .  gracias ..
s

2021-02-04 22:23 UTC, Julima15 commented
ya quedo validado por ux, podes corregir el pr :)

2021-02-05 17:26 UTC, Julima15 commented
uh me falta etiquetarte @jbrunoAtMeli en el mensaje anterior :D

2021-02-05 20:26 UTC, jbrunoAtMeli reviewed
el último paso borrar estas lineas en blanco y lo merge!!

2021-02-05 20:26 UTC, jbrunoAtMeli commented on Example/AndesUI/UITabBarItem+AndesBadgeExtension/Views/AndesBadgeExtensionTabBarController.swift
> +
@Julima15 Podes borrar los espacios? Los que veas no "útiles" como este ?

2021-02-08 13:16 UTC, Julima15 commented on Example/AndesUI/UITabBarItem+AndesBadgeExtension/Views/AndesBadgeExtensionTabBarController.swift
> +
@jbrunoAtMeli ahi borre las lineas en blanco que considero que no afectan la lectura del codigo

2021-02-08 13:57 UTC, jbrunoAtMeli approved these changes

2021-02-08 13:57 UTC, merged