Feature/analytics
mercadolibre/fury_andesui-ios pull request #242
Opened 2021-03-08 16:23 UTC by dabeltran95

### Thanks for contributing to Andes UI!
## Description
Describe why we need these changes in the lib.
Try to answer these questions:
- What is it about?
- se añadió analítica con firebase a la testApp
- How does it work?
- Se modificaron algunos routers de los componentes , para poder enviar el evento de la misma forma en todos.
- Se creo una clase 'AnalyticsHelper' desde la cual se lanza el evento a firebase 
- El encargado de obtener la info del evento es 'AndesShowcasePageViewController' .
## Affected component
Is highly probable that this new code affects directly one (or more?) components inside this lib. Tell us who they are!
- AndesShowcasePageViewController
## Variant component
Tell us which variant improved or is new!
## RFC Link
If this change was discussed on RFC please paste link here.
## Screenshots / GIFs
This is a UI library, delight us with some stunning images.
## Checks
Are you sure you followed all those steps? If so, repeat after me "I solemnly swear that ...":
   - [. ] I have coded an example inside the Demo App.
   - [ ] I have added proper tests.
   - [ .] I have modified the Changelog.md file.
   - [ ] I have updated GitHub wiki.
   - [ ] I have the explicit approval of one or more members of the UX Team.
   - [ .] I have notify Andes team for PR.
   - [ ] I have checked that this code is ObjC compliant.
   - [ ] I have checked that all the new public enums conform to AndesEnumStringConvertible.
## Change type
This is easy, let us know what this code is about:
   - [ ] This code adds a new component
   - [ ] This code includes improvements to an existent component
   - [ .] This code improves or modifies ONLY the Demo App.

2021-03-08 19:44 UTC, joalonsopint commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +        }
Y si te dejas ese View como optional, para no crear esa variable screen?, así reduces un poco el método

2021-03-08 19:53 UTC, joalonsopint commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +                currentSeconds += currentComponentSeconds[screen]!
Podríamos tratar que no tenga este forzado?, algo así?
if let currentScreen = currentComponentSeconds[screen] {
       currentSeconds += currentScreen
}

2021-03-08 20:04 UTC, joalonsopint commented on Example/AndesUI/PageController/AndesShowcasePageViewController.swift
> +        guard let currentController = pageContentViewController.nibName else { return }
Qué tal este Guard así?
guard let pageContentViewController = pageViewController.viewControllers?.first!, let currentController = pageContentViewController.nibName else { return }

2021-03-08 20:07 UTC, joalonsopint commented on Example/AndesUI/UITabBarItem+AndesBadgeExtension/Views/AndesBadgeExtensionTabBarController.swift
> +        super.init(nibName: "AndesBadgeExtensionTabBarController", bundle: nil)
No estoy muy seguro aquí, no falla por no existir el .xib?

2021-03-08 20:10 UTC, joalonsopint commented on Example/AndesUI/Base.lproj/LaunchScreen.xib
> +        </systemColor>
Esto que nos afecta?

2021-03-08 21:46 UTC, dabeltran95 commented on Example/AndesUI/UITabBarItem+AndesBadgeExtension/Views/AndesBadgeExtensionTabBarController.swift
> +        super.init(nibName: "AndesBadgeExtensionTabBarController", bundle: nil)
lo puse por que en el AndesShowcasePageViewController necesito saber que ViewController esta presente , y obtengo el nombre con el nibname... podría cambiarlo por traer el debug description y filtrar el nombre desde ahi. peeero me sigue pareciendo mejor la opción de ponerle nibName, ¿que opinas?
"igual no va a estallar por que lo unico que hacemos es un init, solo que le paso de el parametro de nombre" se lo paso o no igual se inicializa

2021-03-09 14:27 UTC, dabeltran95 commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +        }
👌🏼

2021-03-09 14:28 UTC, dabeltran95 commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +                currentSeconds += currentComponentSeconds[screen]!
👌🏼

2021-03-09 14:28 UTC, dabeltran95 commented on Example/AndesUI/PageController/AndesShowcasePageViewController.swift
> +        guard let currentController = pageContentViewController.nibName else { return }
👌🏼

2021-03-09 14:28 UTC, dabeltran95 commented on Example/AndesUI/Base.lproj/LaunchScreen.xib
> +        </systemColor>
se me colo ese cambio, pero ya lo quite

2021-03-09 14:31 UTC, joalonsopint commented on Example/AndesUI/UITabBarItem+AndesBadgeExtension/Views/AndesBadgeExtensionTabBarController.swift
> +        super.init(nibName: "AndesBadgeExtensionTabBarController", bundle: nil)
Dale ;)

2021-03-09 17:40 UTC, jbrunoAtMeli commented on Example/AndesUI/BottomSheet/Views/BottomSheetExampleScrollableContentViewController.swift
> +        self.title = "BottomSheetExampleScrollableContentViewController"
nos llevamos el titulo puede ser más amigable y no tan técnico

2021-03-09 17:42 UTC, jbrunoAtMeli commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +//        Analytics.logEvent(component, parameters: viewsAndSeconds)
es un TODO? marcalo sino borrarlo

2021-03-09 17:47 UTC, jbrunoAtMeli commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +    // swiftlint:disable weak_delegate
este delegate sigue siendo strong?

2021-03-09 17:49 UTC, jbrunoAtMeli reviewed
agrega los otros cambios que hiciste al changelog (los fix también)

2021-03-09 17:51 UTC, dabeltran95 commented on Example/AndesUI/BottomSheet/Views/BottomSheetExampleScrollableContentViewController.swift
> +        self.title = "BottomSheetExampleScrollableContentViewController"
te refieres a sin el viewcontroller ?

2021-03-09 17:51 UTC, dabeltran95 commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +    var screensAndTimers =  [String: Date]()
solo el archivo, bien ahi, ya lo cambio ajajja

2021-03-09 17:54 UTC, dabeltran95 commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +    // swiftlint:disable weak_delegate
este la verdad no se, solo se hizo el cambio del espacio , pero ya miro

2021-03-09 19:35 UTC, jbrunoAtMeli commented on Example/AndesUI/BottomSheet/Views/BottomSheetExampleScrollableContentViewController.swift
> +        self.title = "BottomSheetExampleScrollableContentViewController"
me refiero a lo que mostramos en pantalla

2021-03-09 19:52 UTC, jbrunoAtMeli commented on LibraryComponents/Classes/Core/AndesList/AndesList.swift
> +    // swiftlint:disable weak_delegate
out of scope

2021-03-09 20:09 UTC, jbrunoAtMeli submitted a review, later dismissed
No se si @joalonsopint Quiere pegarle una  mirada

2021-03-09 22:25 UTC, joalonsopint commented
Yo lo veo bien, pero antes de hacer merge, hablen con Tincho, por que está haciendo unas pruebas con la forma default que tiene Firebase para los eventos.

2021-03-12 20:27 UTC, cvillamilmeli requested changes
Te deje unos comentarios para que los revises por fa.

2021-03-12 20:27 UTC, cvillamilmeli commented on Example/AndesUI/Badges/Router/BadgesRouter.swift
> +        viewController.title = "AndesBadge"
Conoces alguna forma de evitar "hardcoded" strings?, lo revisas por fa, dejo un link de apoyo [https://stackoverflow.com/questions/60220095/swift-what-is-the-best-approach-for-remove-hardcoded-string](url)

2021-03-12 20:27 UTC, cvillamilmeli commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +    case staticScreem = "static"
```suggestion
    case staticScreen = "static"
```

2021-03-12 20:27 UTC, cvillamilmeli commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +        "TooltipObjcViewController": "",
Por que este no tiene categoría?

2021-03-12 20:27 UTC, cvillamilmeli commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +        "TextFieldsCodeViewController": "'\'dynamic",
que te parece si el diccionario es de tipos Class, ScreenTypeEvent ?, así podríamos enviar la clase como tal, y el valor nos daría el tipo del enumerador, que te parece?

2021-03-12 20:27 UTC, cvillamilmeli commented on Example/AndesUI/PageController/AndesShowcasePageViewController.swift
> +    private func manageEventTimerWith(action timerAction: TimerAction, for view: String? = nil) {
estás llamando a este método en algún lugar?, no vi usos.

2021-03-12 20:27 UTC, cvillamilmeli commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +    func stopTimer(component: String) {
Revisa si estas funciones son necesarias luego del cambio que damos toda esa responsabilidad a Firebase

2021-03-12 20:27 UTC, cvillamilmeli commented on Example/AndesUI/PageController/AndesShowcasePageViewController.swift
> +        print(currentController)
Tenemos que usar estos prints para algo?

2021-03-15 14:30 UTC, dabeltran95 commented on Example/AndesUI/Badges/Router/BadgesRouter.swift
> +        viewController.title = "AndesBadge"
page not found ajajaj, pues cris a mi no me parece tan necesario dato que es el titulo y es una clase super pequeña , pero si quieres la cambio... podria meter un enum con todos los titulos de todos los componentes ..

2021-03-15 16:51 UTC, dabeltran95 commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +        "TooltipObjcViewController": "",
se me fue pero ya lo corrijo :D

2021-03-15 16:52 UTC, dabeltran95 commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +        "TextFieldsCodeViewController": "'\'dynamic",
no funcionaria para todos los casos, por que habría que igual concatenar strings, aunque me gusta por que si se evitaria el error de tipeo... voy a probarlo ajaja

2021-03-15 16:52 UTC, dabeltran95 commented on Example/AndesUI/PageController/AndesShowcasePageViewController.swift
> +    private func manageEventTimerWith(action timerAction: TimerAction, for view: String? = nil) {
nop, ya lo elimine con otros varios de antes

2021-03-15 16:52 UTC, dabeltran95 commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +    func stopTimer(component: String) {
eliminadas :D

2021-03-15 16:52 UTC, dabeltran95 commented on Example/AndesUI/PageController/AndesShowcasePageViewController.swift
> +        print(currentController)
solo debug, eliminados :D

2021-03-16 15:09 UTC, cvillamilmeli requested changes
Cambiar el nombre de la clase que quedó mal

2021-03-16 15:09 UTC, cvillamilmeli commented on Example/AndesUI/Badges/Router/BadgesRouter.swift
> +        viewController.title = Commons.ComponentsTittle.andesBadge
```suggestion
        viewController.title = Commons.ComponentsTitle.andesBadge
```

2021-03-18 16:17 UTC, nrostanml requested changes

2021-03-18 16:17 UTC, nrostanml commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +                                        AnalyticsParameterItemCategory: languaje])
lint falla por esto

```suggestion
    private func sendNewTrack(screenClass: String, screenName: String, languaje: String) {
        Analytics.logEvent(AnalyticsEventScreenView,
                           parameters: [AnalyticsParameterScreenName: screenName,
                                        AnalyticsParameterScreenClass: screenClass,
                                        AnalyticsParameterItemCategory: languaje])
```

2021-03-18 20:26 UTC, nrostanml approved these changes

2021-03-18 20:58 UTC, joalonsopint approved these changes

2021-03-18 21:00 UTC, nrostanml requested changes

2021-03-18 21:00 UTC, nrostanml commented on Example/AndesUI/Helper/AnalitycsHelper.swift
> +//  AnalitycsHelper.swift
esta clase tiene un tipo, es Analytics no analitycs

2021-03-18 22:01 UTC, cvillamilmeli approved these changes

2021-03-18 22:07 UTC, nrostanml approved these changes

2021-03-18 22:08 UTC, cvillamilmeli approved these changes

2021-03-18 22:16 UTC, merged