Feature/AndesMessage Thumbnail
mercadolibre/fury_andesui-ios pull request #249
Opened 2021-03-22 14:53 UTC by javff

### Thanks for contributing to Andes UI!
## Description
Add thumbnail variant in AndesMessage
Try to answer these questions:
- What is it about?
- How does it work?
## Affected component
Is highly probable that this new code affects directly one (or more?) components inside this lib. Tell us who they are!
## Variant component
Tell us which variant improved or is new!
## RFC Link
If this change was discussed on RFC please paste link here.
## Screenshots / GIFs

| default | with-actions  | with-bullets |
| --- | --- | --- | 
![simulator_screenshot_88405943-69C5-4DDD-8644-40354EF4652F](https://user-images.githubusercontent.com/18092648/112008821-97551e00-8b04-11eb-9c3f-5f837efe5114.png) | ![simulator_screenshot_ED525C7B-B1A6-4946-A912-376F7CCB0BA9](https://user-images.githubusercontent.com/18092648/112008785-90c6a680-8b04-11eb-9b0e-7fc61e884894.png) | ![simulator_screenshot_17351807-69E7-41F6-8496-C58A48F9DA38](https://user-images.githubusercontent.com/18092648/112008869-a5a33a00-8b04-11eb-93a1-20c312f61aa9.png) |

| examples |
| --- | 
![simulator_screenshot_CF6380F5-EACA-4580-8329-FA3E03323E9C](https://user-images.githubusercontent.com/18092648/112008893-ab991b00-8b04-11eb-8f96-d1ceb12857b4.png)

## Checks
Are you sure you followed all those steps? If so, repeat after me "I solemnly swear that ...":
   - [ ] I have coded an example inside the Demo App.
   - [ ] I have added proper tests.
   - [ ] I have modified the Changelog.md file.
   - [ ] I have updated GitHub wiki.
   - [ ] I have the explicit approval of one or more members of the UX Team.
   - [ ] I have notify Andes team for PR.
   - [ ] I have checked that this code is ObjC compliant.
   - [ ] I have checked that all the new public enums conform to AndesEnumStringConvertible.
## Change type
This is easy, let us know what this code is about:
   - [ ] This code adds a new component
   - [ ] This code includes improvements to an existent component
   - [ ] This code improves or modifies ONLY the Demo App.

2021-03-23 14:40 UTC, dabeltran95 commented on Example/AndesUI/Messages/Views/MessageObjCViewController.m
> +}
```suggestion
    }
```

2021-03-23 14:41 UTC, dabeltran95 commented on Example/AndesUI/Messages/Views/MessageObjCViewController.m
> +}
error de identacion

2021-03-23 15:30 UTC, javff commented on Example/AndesUI/Messages/Views/MessageObjCViewController.m
> +
buena ahi lo acomodo.

2021-03-23 15:31 UTC, javff commented on Example/AndesUI/Messages/Views/MessageObjCViewController.m
> +}
el espaciado en este caso esta bien, este archivo es .m y es el nivel de identación de los métodos.

2021-03-23 20:47 UTC, dabeltran95 approved these changes

2021-03-25 16:52 UTC, dabeltran95 requested changes
Olvidaste modificar el CHANGELOG.md añadiendo lo que hiciste :D

2021-03-25 19:48 UTC, dabeltran95 approved these changes

2021-03-25 20:51 UTC, merged